# I will combine all files (frontend,backend and mongoDB) into one yaml file for orchestration

# 1. Frontend (Deployment and Service) --copied the template from kubernetes docs to help me in editing to avoid making errors of identation
apiVersion: apps/v1   #Tells kubernetes which API group and version my manifest is written for
kind: Deployment      # The kubernetes controller that manages pods
metadata:
  name: vincent-yolo-client  # Deployment name that identifies this object uniquely
spec: # This are instructions that tell Kubernetes what the Deployment should do and how the Pods it manages should be set up
  selector:
    matchLabels:
      app: vincent-yolo-client
  replicas: 2 # tells deployment to run 2 identical pods at all times
  template:
    metadata:
      labels:
        app: vincent-yolo-client  # The Pods will be labeled app=vincent-yolo-client
    spec: # this is pod specifications. This pod only runs one container
      containers:
      - name: vincent-yolo-client   # name of the container
        image: vokemwa/vincent-yolo-client:v1.0.0 # Pull this Docker image from Docker Hub
        ports:
        - containerPort: 80 # The container will listen on port 80 internally

---
# Frontend Service
# A service is like a parmanent address for the pods. This service directs traffic to our pod "vincent-yolo-client" 
# transfered the service template from kubernetes docs to help me avoid identation errors

apiVersion: v1  # v1 is the stable version in API group
kind: Service   # this object is a service which is a stable network endpoint for pods
metadata:
  name: vincent-yolo-client-service  # The service will be called 
spec:
  type: LoadBalancer  # Kubernetes will provision an external load balancer that will get an external IP address so it’s accessible from the internet.
  selector:
    app.kubernetes.io/name: vincent-yolo-client  # This Service will route traffic to all Pods with the label app=vincent-yolo-client
  ports:
    - protocol: TCP
      port: 3000  # The port exposed by the Service to the outside world
      targetPort: 80 # The port inside the Pods’ containers that the Service forwards to

---

## create a deployment for the backend (Deployment)

apiVersion: apps/v1  # version v1 — the stable API for Deployments
kind: Deployment     # manages Pods and their ReplicaSets, ensuring a desired number are running and up-to-date
metadata:
  name: vincent-yolo-backend  # Deployment’s name is vincent-yolo-backend
spec:
  replicas: 2   # Run 2 Pods at all times for redundancy/high availability
  selector:
    matchLabels:
      app: vincent-yolo-backend  # checks for pods by label "vincent-yolo-backend"
  template:
    metadata:
      labels:
        app: vincent-yolo-backend
    spec:
      containers:
        - name: vincent-yolo-backend   # Container name
          image: vokemwa/vincent-yolo-backend:v1.0.0 # docker image from dockerhub registry
          ports:
            - containerPort: 5000  # this container listens on 5000 for incoming requests
          env:
            - name: MONGO_URL
              value: mongodb://vincent-app-ip-mongo-service:27017   # default port for mongodb

---

## backend service
apiVersion: v1
kind: Service   # this is a service: a stable way to access pods by name even if there is a change in pod IP
metadata:
  name: vincent-yolo-backend-service # the name of the service will be "vincent-yolo-backend-service"
spec:
  selector:
    app: vincent-yolo-backend # This service will forward traffic to pods with labels "vincent-yolo-backend" which is actually the name of the deployment
  ports:
    - protocol: TCP
      port: 5000    # This actually is the port in the service that clients connect to
      targetPort: 5000 # the port inside the container where the app is listening