#SPDX-License-Identifier: MIT-0
---
# vars file for Backend_deployment_settings
#define variables that will be used in the tasks yaml file
container_name: vincent-yolo-backend
network: vincent-network
